API_ID: 21432914
API_HASH: 4d65415fcce04e8076acee5b6688c1b1
BOT_TOKEN: 6930471158:AAG3q5sDezB-UHsO2YMsC-IERNqfF3OlTWE


MONGO_URL: mongodb+srv://EXONTESTMONGO:EXONTESTMONGO@cluster0.bviw7ic.mongodb.net/?retryWrites=true&w=majority
REDIS_URI:redis-13363.c270.us-east-1-3.ec2.redns.redis-cloud.com:13363
REDIS_PORT:13363
REDIS_PASS:pODqcQUfvyB5svb5ycDdaP5Jv1zhaQOZ

SESSION_API_ID: 21432914
SESSION_API_HASH: 4d65415fcce04e8076acee5b6688c1b1
SESSION_STRING: BQFHClIAjBlVe-Er-WOBRzbgBVLXmPJDfQunWQKZZGh7qHTfUf6R8Mh2YkKX9luqZe6o-2OslS8UaziCVfFlyIpoc_m2p5T6QRApiayrpHc0dK9Cl4dWl5a_ZfAObo3-O8sxWc28IJ-GVvITwjDuNVZBvuXc34b0jnvE9xroSByHhdUCp7M0RYAPHFK3uGmMrJgT1wAtGdCA_akuSGaJogBGpkF4N9ajg0vglcx96wdgJoUoO2uJ_GgeyEkGeqq2_pqN-CHtomUtRfPkbhM48mNG4uI53rU-4G4dvBnh20w-8Thd3QW8eNYy_3XAkypuQOAdVdaE0Lz-n3PujZ6Z4lj0AlszFQAAAAFO0ERhAA

ADMINS: 6035523795
  - 1317173146

OWNER: 6035523795

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: nxtbots 
# LOG_CHAT: 
LOG_CHAT: -1001632371325



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

