API_ID: 
API_HASH: 
BOT_TOKEN: 1765254636:AAG7Eo6W9PASHJKMeswtVasm7WQbM3Gr6Ac 


MONGO_URL: 
REDIS_URI:
REDIS_PORT:
REDIS_PASS:

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 1822924664

OWNER: 1822924664

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

