API_ID: 21432914
API_HASH: 4d65415fcce04e8076acee5b6688c1b1
BOT_TOKEN: 6930471158:AAG3q5sDezB-UHsO2YMsC-IERNqfF3OlTWE


MONGO_URL: mongodb+srv://EXONTESTMONGO:EXONTESTMONGO@cluster0.bviw7ic.mongodb.net/?retryWrites=true&w=majority
REDIS_URI:redis-13363.c270.us-east-1-3.ec2.redns.redis-cloud.com:13363
REDIS_PORT:13363
REDIS_PASS:pODqcQUfvyB5svb5ycDdaP5Jv1zhaQOZ

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 1317173146

OWNER: 1317173146

BOT_PIC: https://te.legra.ph/file/a44cc6ec55eeafec0c558.jpg
OWNER_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg


SUPPORT_CHAT: roldexversechats 
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

